feat(ci): add merge test to release workflow (#11)

diff --git a/.circleci/commands/git-merge-branch.yml b/.circleci/commands/git-merge-branch.yml
--- a/.circleci/commands/git-merge-branch.yml
+++ b/.circleci/commands/git-merge-branch.yml
@@ -10,6 +10,9 @@ parameters:
   trigger_ci:
     type: boolean
     default: true
+  simulate:
+    type: boolean
+    default: false
 steps:
   - run:
       name: merge to '<< parameters.base_branch >>'
@@ -19,16 +22,21 @@ steps:
         git checkout "<< parameters.merge_branch >>" && git pull
         git checkout "<< parameters.base_branch >>" && git pull
 
+        merge_args="--no-verify --no-ff -m 'chore(release): merge << parameters.tag >>'"
+
         case << parameters.trigger_ci >> in
-          false) trigger="[ci skip]";;
-          *) trigger="";;
+          false) merge_args="$merge_args -m '[ci skip]'";;
         esac
 
-        git merge \
-            --no-verify \
-            --no-ff \
-            -m "chore(release): merge << parameters.tag >>" \
-            -m "$trigger" \
-            "<< parameters.merge_branch >>"
+        if << parameters.simulate >> then;
+          merge_args="--no-commit $merge_args"
+        fi
+
+        result=$(git merge $merge_args "<< parameters.merge_branch >>" || echo "[merge-failed]")        
+        if [[ "$result" =~ \[merge-failed\] ]]; then
+          echo $result
+          git reset --hard
+          exit 1
+        fi
 
         git push
diff --git a/.circleci/config.yml b/.circleci/config.yml
--- a/.circleci/config.yml
+++ b/.circleci/config.yml
@@ -20,6 +20,9 @@ commands:
         type: string
       merge_branch:
         type: string
+      simulate:
+        default: false
+        type: boolean
       tag:
         default: ${RELEASE_VERSION}
         type: string
@@ -28,25 +31,15 @@ commands:
         type: boolean
     steps:
     - run:
-        command: |
-          echo "merging << parameters.merge_branch >> into '<< parameters.base_branch >>'"
-          git fetch --all
-          git checkout "<< parameters.merge_branch >>" && git pull
-          git checkout "<< parameters.base_branch >>" && git pull
-
-          case << parameters.trigger_ci >> in
-            false) trigger="[ci skip]";;
-            *) trigger="";;
-          esac
-
-          git merge \
-              --no-verify \
-              --no-ff \
-              -m "chore(release): merge << parameters.tag >>" \
-              -m "$trigger" \
-              "<< parameters.merge_branch >>"
-
-          git push
+        command: "echo \"merging << parameters.merge_branch >> into '<< parameters.base_branch
+          >>'\"\ngit fetch --all\ngit checkout \"<< parameters.merge_branch >>\" &&
+          git pull\ngit checkout \"<< parameters.base_branch >>\" && git pull\n\nmerge_args=\"--no-verify
+          --no-ff -m 'chore(release): merge << parameters.tag >>'\"\n\ncase << parameters.trigger_ci
+          >> in\n  false) merge_args=\"$merge_args -m '[ci skip]'\";;\nesac\n\nif
+          << parameters.simulate >> then;\n  merge_args=\"--no-commit $merge_args\"\nfi\n\nresult=$(git
+          merge $merge_args \"<< parameters.merge_branch >>\" || echo \"[merge-failed]\")
+          \       \nif [[ \"$result\" =~ \\[merge-failed\\] ]]; then\n  echo $result\n
+          \ git reset --hard\n  exit 1\nfi\n\ngit push\n"
         name: merge to '<< parameters.base_branch >>'
   git-set-identity:
     parameters:
@@ -203,6 +196,14 @@ jobs:
           echo "export RELEASE_BRANCH_NAME=$(cat ./RELEASE_BRANCH_NAME)" >> $BASH_ENV
           echo "export RELEASE_VERSION=$(cat ./RELEASE_VERSION)" >> $BASH_ENV
         name: set release info
+    - git-merge-branch:
+        base_branch: develop
+        merge_branch: $RELEASE_BRANCH_NAME
+        simulate: true
+    - git-merge-branch:
+        base_branch: master
+        merge_branch: $RELEASE_BRANCH_NAME
+        simulate: true
     - git-merge-branch:
         base_branch: develop
         merge_branch: $RELEASE_BRANCH_NAME
